name: jest-and-docker-ci

on: push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      - name: âœ… Check out code
        uses: actions/checkout@v2
      - name: âš™ï¸ Goto client and run tests
        run: cd client && npm i && npm test
  docker:
    needs: test-front
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›  Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: âš¡ï¸ Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: ğŸŒ± Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/quete1902:latest
